[2022-07-05 16:54:54,085] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: twitter_dag.request_twitter_data manual__2022-07-05T19:54:51.187836+00:00 [queued]>
[2022-07-05 16:54:54,090] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: twitter_dag.request_twitter_data manual__2022-07-05T19:54:51.187836+00:00 [queued]>
[2022-07-05 16:54:54,090] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 16:54:54,090] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2022-07-05 16:54:54,090] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-05 16:54:54,114] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): request_twitter_data> on 2022-07-05 19:54:51.187836+00:00
[2022-07-05 16:54:54,116] {standard_task_runner.py:52} INFO - Started process 23275 to run task
[2022-07-05 16:54:54,121] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'request_twitter_data', 'manual__2022-07-05T19:54:51.187836+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp27mcex06', '--error-file', '/tmp/tmpjln_v_7u']
[2022-07-05 16:54:54,121] {standard_task_runner.py:80} INFO - Job 26: Subtask request_twitter_data
[2022-07-05 16:54:54,202] {task_command.py:370} INFO - Running <TaskInstance: twitter_dag.request_twitter_data manual__2022-07-05T19:54:51.187836+00:00 [running]> on host nicholas-VirtualBox
[2022-07-05 16:54:54,271] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nicholas.comuni@outlook.com
AIRFLOW_CTX_DAG_OWNER=Nicholas
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=request_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-05T19:54:51.187836+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-05T19:54:51.187836+00:00
[2022-07-05 16:54:55,007] {logging_mixin.py:115} INFO - /tmp/tmpkyyy7j2i/covid19.json
[2022-07-05 16:54:55,007] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 35, in request_twitter_data
    filename = f"{hashtag.replace('#','')}/{datetime.now().year}/{datetime.now().month}/{hashtag.replace('#','')}_{datetime.now().replace(':','_')}.json"
TypeError: 'str' object cannot be interpreted as an integer
[2022-07-05 16:54:55,011] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=request_twitter_data, execution_date=20220705T195451, start_date=20220705T195454, end_date=20220705T195455
[2022-07-05 16:54:55,026] {standard_task_runner.py:92} ERROR - Failed to execute job 26 for task request_twitter_data ('str' object cannot be interpreted as an integer; 23275)
[2022-07-05 16:54:55,047] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-05 16:54:55,068] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
